function [fitresult, gof] = createFit_default(avgR)
%CREATEFIT(AVGR)
%  Create a fit.
%
%  Data for 'fitTest' fit:
%      Y Output: avgR
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2020 18:26:03


%% Fit: 'fitTest'.
[xData, yData] = prepareCurveData( [], avgR );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.9;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'fitTest' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'avgR', 'fitTest', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'avgR', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'fitTest - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'avgR', 'Interpreter', 'none' );
grid on


