function [fitresult, gof,output] = createFitExp(input)
%CREATEFIT1(TEST)
%  Create a fit.
%
%  Data for 'fit2' fit:
%      Y Output: test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2020 20:02:30

plotFigure=0;

input=double(input);
if size(input,1)>size(input,2)
   input=input'; 
end

[xData, yData] = prepareCurveData( [], input );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
% opts.Robust = 'LAR';
% opts.StartPoint = [31.2434354557883 -1.03798009380285 1860.66061166216 -0.00557343180828299];

% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft, opts );


if plotFigure
% Create a figure for the plots.
figure( 'Name', 'Spline Fitting' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'input', 'fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'input', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'fitTest - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'input', 'Interpreter', 'none' );
grid on
end

