function [fitresult, gof,output] = createFit(input)
%CREATEFIT(input)
%  Create a fit on 1D input
%
%  Data for 'fitTest' fit:
%      Y Output: input
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2020 18:39:27

plotFigure=1;
%% Fit: 'fitTest'.

input=double(input);

[xData, yData] = prepareCurveData( [], input );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = 0.9;

% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft, opts );
% 

if plotFigure
% Create a figure for the plots.
figure( 'Name', 'Spline Fitting' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'input', 'fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'input', 'Interpreter', 'none' );
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'fitTest - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
ylabel( 'input', 'Interpreter', 'none' );
grid on
end

