function metadata = importLVmetadata(filename, dataLines)
%IMPORTFILE Import data from a text file
%  METADATA = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a string array.
%  
%  METADATA = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%  e.g. use dataLines=[9 11]; to access only LED power
%
%  Example:
%  metadata = importLVmetadata("F:\GEVI_Wave\Preprocessed\Visual\m19\20210322\meas00\LVmeta\metadata.txt", [1, Inf]);
%  
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Mar-2021 13:24:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ["\t", ";"];

% Specify column names and types
opts.VariableNames = ["DCIMGfilepath", "Var2", "DGEVI_WaveRawVisualm1920210322meas00m19_d210322_s00visGammafps2"];
opts.SelectedVariableNames = ["DCIMGfilepath", "DGEVI_WaveRawVisualm1920210322meas00m19_d210322_s00visGammafps2"];
opts.VariableTypes = ["string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
metadata = readtable(filename, opts);

%% Convert to output type
metadata = table2array(metadata);
end