function [fitresult, gof,output] = createSplineFit(timeStamps, trace)
%CREATEFIT1(TIME,TEST)
%  Create a fit.
% plotFigure
%  Data for 'untitled fit 1' fit:
%      X Input : time
%      Y Output: test
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Feb-2021 15:08:06


%% Fit: 'untitled fit 1'.

plotFigure=1;

trace=double(trace);

if size(trace,1)>size(trace,2)
   trace=trace'; 
end

[xData, yData] = prepareCurveData( timeStamps, trace );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.1;

% Fit model to data.
[fitresult, gof,output] = fit( xData, yData, ft, opts );

if plotFigure
% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'test vs. time', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'test', 'Interpreter', 'none' );
grid on
end


end
